version: '2'

networks:
  ca_fchain:
volumes:
  ca_root.lianxiang.com:

services:

  ca_root.lianxiang.com:
    image: hyperledger/fabric-ca:${CA_IMAGE_TAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_root.lianxiang.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=${CA_PORT}
    ports:
      - ${CA_PORT}:${CA_PORT}
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ca_root.lianxiang.com:/etc/hyperledger/fabric-ca-server
    container_name: ca_root.lianxiang.com
    networks:
      - ca_fchain

